import PDFDocument from "pdfkit";

export const generateInvoicePdf = (invoice) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ size: "A4", margin: 50 });

            const buffers = [];
            doc.on("data", buffers.push.bind(buffers));
            doc.on("end", () => resolve(Buffer.concat(buffers)));

            /* ================= HEADER ================= */

            doc.font("Helvetica-Bold").fontSize(14).text("SRS LOGISTICS AND STORAGE LTD");
            doc.fontSize(10).font("Helvetica").text(
                `Unit 12 Farringdon Grove
Farringdon Avenue
Romford
RM3 8TD`
            );

            doc.moveDown(0.5);
            doc.text("Company VAT no: 321 6802 29");
            doc.text("Company Registration: 11762532");

            doc.moveDown();
            drawLine(doc);

            /* ================= META ================= */

            doc.moveDown();
            doc.text(`Invoice date: ${formatDate(Date.now())}`);
            doc.text(`Bill pay date: ${formatDate(Date.now()+(1000*60*60*24*7))}`);

            doc.moveDown();
            doc.font("Helvetica-Bold").text(`Name: ${invoice.name}`);
            doc.font("Helvetica").text(`NI Number: ${invoice.niNumber}`);
            doc.text(`Address: ${invoice.address}`);
            doc.text(`VAT number: ${invoice.vatNumber || "N/A"}`);

            doc.moveDown();
            drawLine(doc);

            /* ================= TABLE HEADER ================= */

            const tableTop = doc.y;
            const col = {
                day: 50,
                date: 90,
                desc: 190,
                amount: 450,
            };

            doc.font("Helvetica-Bold").fontSize(10);
            doc.text("Day", col.day, tableTop);
            doc.text("Date", col.date, tableTop);
            doc.text("Description", col.desc, tableTop);
            doc.text("Amount", col.amount, tableTop, { align: "right" });

            doc.moveDown(0.5);
            drawLine(doc);

            /* ================= TABLE BODY ================= */

            doc.font("Helvetica").fontSize(10);

            let totalServiceAmount = 0;

            invoice.data.weekData.forEach((day) => {
                if (!day.assignments?.length) return;

                const dayTotal = day.assignments.reduce(
                    (sum, a) => sum + Number(a.rate || 0),
                    0
                );

                totalServiceAmount += dayTotal;

                doc.text(day.weekday.slice(0, 3), col.day);
                doc.text(formatDate(day.date), col.date);
                doc.text(
                    day.assignments.map(a => a.detailRoute).join(", "),
                    col.desc
                );
                doc.text(`${dayTotal.toFixed(2)}£`, col.amount, undefined, {
                    align: "right",
                });

                doc.moveDown(0.4);
            });

            drawLine(doc);

            /* ================= TOTALS ================= */

            doc.moveDown();

            drawRightRow(doc, "Total Service Amount", `${invoice.earnings.weeklyTotal.toFixed(2)}£`);
            drawRightRow(doc, "VAT Amount", `${invoice.earnings.vatAmount.toFixed(2)}£`);
            drawRightRow(doc, "CTP Payment", `${invoice.earnings.ctpPayment.toFixed(2)}£`);
            drawRightRow(doc, "Liability for this Week", `${invoice.summary.totalScheduledDeductions.toFixed(2)}£`);
            drawRightRow(doc, "Deducted This Week", `${invoice.summary.totalDeducted.toFixed(2)}£`);
            drawRightRow(doc, "Carry Forward to Next Week", `${invoice.summary.totalCarryForward.toFixed(2)}£`);


            drawLine(doc);

            drawRightRow(
                doc,
                "Grand Total",
                `${invoice.summary.netPayment.toFixed(2)}£`,
                true
            );

            /* =============================== FOOTER=============================== */

            drawLine(doc);

            doc
                .fontSize(9)
                .font("Helvetica")
                .text("Generated by SRS Management System", { align: "center" });

            doc.text(
                `Printed on: ${new Date().toLocaleString()}`,
                { align: "center" }
            );

            doc.end();
        } catch (err) {
            reject(err);
        }
    });
};



/* ================= HELPERS ================= */

function drawLine(doc) {
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
}

function drawRightRow(doc, label, value, bold = false) {
    doc.font(bold ? "Helvetica-Bold" : "Helvetica");
    doc.text(label, 300);
    doc.text(value, 50, doc.y, { align: "right", width: 495 });
    doc.moveDown(0.3);
}

function formatDate(date) {
    return new Date(date).toLocaleDateString("en-GB", {
        day: "2-digit",
        month: "short",
        year: "numeric",
    });
}
