import PDFDocument from "pdfkit";

export const generateInvoicePdf = (invoice) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50 });

      const buffers = [];
      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => resolve(Buffer.concat(buffers)));

      const pageWidth = 545;
      const startX = 50;

      /* ================= HEADER ================= */

      doc.font("Helvetica-Bold").fontSize(14).text("SRS LOGISTICS AND STORAGE LTD");
      doc.fontSize(10).font("Helvetica").text(
        `Unit 12 Farringdon Grove
Farringdon Avenue
Romford
RM3 8TD`
      );

      doc.moveDown(0.5);
      doc.text("Company VAT no: 321 6802 29");
      doc.text("Company Registration: 11762532");

      drawLine(doc);

      /* ================= META ================= */

      doc.moveDown();
      doc.text(`Invoice date: ${formatDate(Date.now())}`);
      doc.text(`Bill pay date: ${formatDate(Date.now() + 7 * 86400000)}`);

      doc.moveDown();
      doc.font("Helvetica-Bold").text(`Name: ${invoice.name}`);
      doc.font("Helvetica").text(`NI Number: ${invoice.niNumber}`);
      doc.text(`Address: ${invoice.address}`);
      doc.text(`VAT number: ${invoice.vatNumber || "N/A"}`);

      drawLine(doc);

      /* ================= TABLE ================= */

      const col = {
        day: 50,
        date: 90,
        desc: 190,
        amount: 450,
      };

      const rowHeight = 22;

      // Header row
      const headerY = doc.y + 5;
      drawTableRowBorder(doc, headerY, rowHeight);

      doc.font("Helvetica-Bold").fontSize(10);
      doc.text("Day", col.day, headerY + 6);
      doc.text("Date", col.date, headerY + 6);
      doc.text("Description", col.desc, headerY + 6);
      doc.text("Amount", col.amount, headerY + 6, {
        align: "right",
        width: 90,
      });

      doc.y = headerY + rowHeight;

      doc.font("Helvetica").fontSize(10);

      let totalServiceAmount = 0;

      invoice.data.weekData.forEach((day) => {
        if (!day.assignments?.length) return;

        if (doc.y > doc.page.height - 150) doc.addPage();

        const dayTotal = day.assignments.reduce(
          (sum, a) => sum + Number(a.rate || 0),
          0
        );

        totalServiceAmount += dayTotal;

        const rowY = doc.y;

        drawTableRowBorder(doc, rowY, rowHeight);

        doc.text(day.weekday.slice(0, 3), col.day, rowY + 6);
        doc.text(formatDate(day.date), col.date, rowY + 6);

        doc.text(
          day.assignments.map(a => a.detailRoute).join(", "),
          col.desc,
          rowY + 6,
          { width: 240 }
        );

        doc.text(`${dayTotal.toFixed(2)}£`, col.amount, rowY + 6, {
          align: "right",
          width: 90,
        });

        doc.y = rowY + rowHeight;
      });

      drawLine(doc);

      /* ================= TOTALS ================= */

      doc.moveDown();

      drawTotalRow(doc, "Total Service Amount", invoice.earnings.weeklyTotal);
      drawTotalRow(doc, "VAT Amount", invoice.earnings.vatAmount);
      drawTotalRow(doc, "CTP Payment", invoice.earnings.ctpPayment);
      drawTotalRow(doc, "Liability for this Week", invoice.summary.totalScheduledDeductions);
      drawTotalRow(doc, "Deducted This Week", invoice.summary.totalDeducted);
      drawTotalRow(doc, "Carry Forward to Next Week", invoice.summary.totalCarryForward);

      drawLine(doc);

      drawTotalRow(doc, "Grand Total", invoice.summary.netPayment, true);

      /* ================= FOOTER ================= */

      const footerY = doc.page.height - 100;

      doc.moveTo(startX, footerY).lineTo(pageWidth, footerY).stroke();

      doc.fontSize(9).font("Helvetica").text(
        "Generated by SRS Management System",
        startX,
        footerY + 10,
        { align: "center", width: 495 }
      );

      doc.text(
        `Printed on: ${new Date().toLocaleString()}`,
        startX,
        footerY + 25,
        { align: "center", width: 495 }
      );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

/* ================= HELPERS ================= */

function drawLine(doc) {
  doc.moveDown(0.7);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.7);
}

function drawTableRowBorder(doc, y, height) {
  doc.rect(50, y, 495, height).stroke();
}

function drawTotalRow(doc, label, value, bold = false) {
  doc.font(bold ? "Helvetica-Bold" : "Helvetica");
  const y = doc.y;

  doc.text(label, 300, y);
  doc.text(`${Number(value || 0).toFixed(2)}£`, 50, y, {
    align: "right",
    width: 495,
  });

  doc.moveDown(0.8);
}

function formatDate(date) {
  return new Date(date).toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}
