// src/services/pdf.service.mjs
import PDFDocument from "pdfkit";

/**
 * Generate invoice PDF in memory (A4)
 * @param {Object} invoice
 * @returns {Promise<Buffer>}
 */
export const generateInvoicePdf = (invoice) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: "A4",
                margin: 50,
            });

            const buffers = [];
            doc.on("data", buffers.push.bind(buffers));
            doc.on("end", () => resolve(Buffer.concat(buffers)));

            /* ===============================
               HEADER
            =============================== */

            doc
                .fontSize(18)
                .font("Helvetica-Bold")
                .text("SRS Management System", { align: "left" });

            doc
                .fontSize(20)
                .text("INVOICE", { align: "right" });

            doc.moveDown(0.5);

            doc
                .moveTo(50, doc.y)
                .lineTo(545, doc.y)
                .stroke();

            doc.moveDown(1);

            /* ===============================
               INVOICE META
            =============================== */

            doc.fontSize(11).font("Helvetica");

            doc.text(`Invoice Reference: ${invoice.reference}`);
            doc.text(`Email: ${invoice.email}`);
            doc.text(`Year: ${invoice.year}   Week: ${invoice.week}`);

            doc.moveDown(1);

            /* ===============================
               EARNINGS SECTION
            =============================== */

            doc.font("Helvetica-Bold").text("Earnings");
            doc.moveDown(0.3);

            drawKeyValue(doc, "Weekly Total", invoice.earnings.weeklyTotal);
            drawKeyValue(doc, "VAT Amount", invoice.earnings.vatAmount);
            drawKeyValue(doc, "CTP Payment", invoice.earnings.ctpPayment);

            drawDivider(doc);

            /* ===============================
               DEDUCTIONS SECTION
            =============================== */

            doc.font("Helvetica-Bold").text("Deductions");
            doc.moveDown(0.3);

            drawKeyValue(doc, "Scheduled Deductions", invoice.summary.totalScheduledDeductions);
            drawKeyValue(doc, "Deducted This Week", invoice.summary.totalDeducted);
            drawKeyValue(doc, "Carry Forward", invoice.summary.totalCarryForward);

            drawDivider(doc);

            /* ===============================
               SUMMARY SECTION
            =============================== */

            //   doc.font("Helvetica-Bold").text("Summary");
            doc.moveDown(0.5);

            //   drawKeyValue(doc, "Total Earnings", invoice.summary.totalEarnings);

            doc.moveDown(0.5);

            // Highlight Net Payable
            // keep current Y once
            const rowY = doc.y;

            // background highlight
            doc
                .rect(50, rowY - 6, 495, 28) // full width row highlight
                .fill("#f3f4f6");

            // reset text color after fill
            doc.fillColor("#000");

            // left label
            doc
                .font("Helvetica-Bold")
                .fontSize(13)
                .text("Net Payable", 55, rowY);

            // right value
            doc
                .font("Helvetica-Bold")
                .fontSize(13)
                .text(`${invoice.summary.netPayment}`, 50, rowY, {
                    align: "right",
                    width: 495,
                });

            // move cursor below row

            doc.moveDown(3);

            /* ===============================
               FOOTER
            =============================== */

            drawDivider(doc);

            doc
                .fontSize(9)
                .font("Helvetica")
                .text("Generated by SRS Management System", { align: "center" });

            doc.text(
                `Printed on: ${new Date().toLocaleString()}`,
                { align: "center" }
            );

            doc.end();
        } catch (err) {
            reject(err);
        }
    });
};

/* ===============================
   HELPER FUNCTIONS
=============================== */

function drawKeyValue(doc, label, value) {
    doc
        .font("Helvetica")
        .fontSize(11)
        .text(label, 50, doc.y, { continued: true });

    doc
        .font("Helvetica")
        .text(String(value ?? 0), {
            align: "right",
            width: 495,
        });

    doc.moveDown(0.3);
}

function drawDivider(doc) {
    doc.moveDown(0.5);
    doc
        .moveTo(50, doc.y)
        .lineTo(545, doc.y)
        .stroke();
    doc.moveDown(0.7);
}
